### ISSUE TITLE
0 commits - .git not repo - WRN partial scan

### ISSUE THREAD

**Issue by ghost** [gitleaks/gitleaks#1055]
hello brother, what is this error? it's not normal

gitleaks detect --source /home/***/***/JSScanner-master/Jsscanner_results/ 

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

4:12PM ERR [git] fatal: .git non è un repository Git (né lo è alcuna delle directory genitrici)
4:12PM INF 0 commits scanned.   
4:12PM ERR  error="git error encountered, see logs"
4:12PM WRN partial scan completed in 84.5ms
4:12PM WRN no leaks found in partial scan

**Comment by weineran** [comment]
If the directory you are scanning it not a git directory, you'll have to use the `--no-git` flag. There is a little more info here: https://github.com/zricethezav/gitleaks#detect

Let us know if that works.

**Comment by zricethezav** [comment]
I didn't know ghosts were real?!
