### ISSUE TITLE
Installing from source doesn't work

### ISSUE THREAD

**Issue by gabohc** [gitleaks/gitleaks#1113]
**Describe the bug**
Installing from source doesn't work

**To Reproduce**
```
git clone https://github.com/zricethezav/gitleaks.git
cd gitleaks
```
Replace `go 1.18` with `go 1.19` because tidy does not support 1.19 (related #1057)
```
sed -i -e 's/go 1.19/go 1.18/g' go.mod 
make build
```
Testing installation with `gitleaks version` outputs `gitleaks: command not found`. Tried adding `chmod +x gitleaks` with no difference.

**Expected behavior**
```
gitleaks version
> 8.16
```

**Basic Info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Gitleaks Version: 8.16

**Additional context**
Related #1057

cc @zricethezav

**Comment by Earl-Wise** [comment]
its not working same issue. any fix?

**Comment by zricethezav** [comment]
`make build` doesn't install globally. You could throw the binary in your `PATH` or run `./gitleaks`

**Comment by rgmz** [comment]
@zricethezav I think you can close this.
