### ISSUE TITLE
Passwords in the code are not detecting using the predefined config file

### ISSUE THREAD

**Issue by priyankavit** [gitleaks/gitleaks#1140]
I'm using the predefined config file (GitleaksUdmCombo.toml) for gitleaks scan, but it is not able to recognize the password information (password key) though it is there in the code. 
1. Could you please share the predefined configuration file for gitleaks scan 
2. and help me how can we identify the password information.

Thanks in advance..!!!!

**Comment by zricethezav** [comment]
> GitleaksUdmCombo.toml

This isn't a file I maintain. 

> Could you please share the predefined configuration file for gitleaks scan

There is a link in the readme

https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml

**Comment by priyankavit** [comment]
[test.txt](https://github.com/gitleaks/gitleaks/files/11155744/test.txt)

- In this yaml file there is DB secret information like password but it is not able to detect the password though it is sensitive information
- I am using the same gitleaks.toml file to recognize the password..it is showing the password in finding but the line number it is referring to and other information is wrong.. we need the abstract information


> Example of console output:
Finding: ..tps://xxx.com
Secret: REDACTED
RuleID: password
Line:109
Commit: XXXXXX
Fingerprint: test.yml:password:109

We dont see the password in line 109 but the actual line number of password information is in different line.
