### ISSUE TITLE
Tagging secrets

### ISSUE THREAD

**Issue by eyalatox** [gitleaks/gitleaks#1146]
It would be nice if the findings had some extra metadata attached to them such as tags.

**Describe the solution you'd like**
here is an example rule with the tags attribute:
```
[[rules]]
description = "PyPI upload token"
id = "pypi-upload-token"
tags = ["registry"]
regex = '''pypi-AgEIcHlwaS5vcmc[A-Za-z0-9\-_]{50,1000}'''
keywords = ["pypi-ageichlwas5vcmc"]
```

cc @zricethezav

I don't mind taking the effort of tagging the existing rules myself if someone else can develop the Go implementation since I'm a Python guy :)

**Comment by zricethezav** [comment]
@eyalatox tags are actually already supported... just not documented in the README >.< 

https://github.com/gitleaks/gitleaks/blob/master/config/rule.go#L31-L33
