### ISSUE TITLE
Feature - Add a new rule to detect Openai API keys

### ISSUE THREAD

**Issue by debasisdwivedy** [gitleaks/gitleaks#1189]
**Is your feature request related to a problem? Please describe.**
Openai provides API keys to access the services for various GenAI tasks

**Describe the solution you'd like**
We would like to add a config/rule to detect if anyone has passed the openai keys in the source code as this can be misused.

**Additional context**
This check for any file with the API keys hardcoded.

cc @zricethezav

**Comment by rgmz** [comment]
The posterity, this was introduced in #1148.
