### ISSUE TITLE
Can't export report file with Docker on Ubuntu

### ISSUE THREAD

**Issue by haidang9b** [gitleaks/gitleaks#1192]
**Describe the bug**
When I run command line on docker with statement 
```
sudo docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --config "/path/gitleaks.toml" -f json -r /path/gitleaks-report.json  --source="/path" -v --exit-code 0 
```
and console show error 
```
225462fcf4bf: Download complete
257f2a88da24: Pull complete
225462fcf4bf: Pull complete
bddc9c379318: Pull complete
Digest: sha256:3ddf2d050a6105f2efb4d5763d8df39c7c32dc8e7b040601999f85e7fc4084fe
Status: Downloaded newer image for zricethezav/gitleaks:latest

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:49AM INF 3 commits scanned.
10:49AM INF scan completed in 71.6ms
10:49AM INF no leaks found
10:49AM FTL could not write error="open /path/gitleaks-report.json: permission denied"
```

**Basic Info (please complete the following information):**
 - OS: Ubuntu
 - Gitleaks Version: latest version from Docker

**Additional context**

I run it on Azure Pipeline command line task

Please help me fix it

cc @zricethezav

**Comment by pacorreia** [comment]
From my experience, running with with/without usod doesn't matter,

you will  need to do chmod 777 to the folder being mounted.

 The UID and GID will be certainly different from host to docker, unless you force specific UID and GID when running docker to match yours.
 
 Give it a try do a chmod 777 to the folder before and then a chmod 777 on the specific file after, that sould do the trick for you

**Comment by haidang9b** [comment]
Many thanks. I know reason of issue, because gitleaks in docker haven't permission access to read/write file. I had change the directory export file to /home/gitleaks/gitleaks-report.json (folder of gitleaks in container)
I fixed it with the statement below:
`sudo docker run -v ${PWD}:/path zricethezav/gitleaks:latest detect --config "/path/gitleaks.toml" -f json -r /home/gitleaks/gitleaks-report.json  --source="/path" -v --exit-code 0 `
