### ISSUE TITLE
jwt can not be detected when length doesn't match the regular expression range

### ISSUE THREAD

**Issue by xiaotaozi1127** [gitleaks/gitleaks#1207]
**Describe the bug**
json web token cannot be detected successfully If the length of the three parts does not match the range specified in the regular expression.

**To Reproduce**
Given jwt value like this: 
`eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJsb2dnZWQtaW4tdXNlciI6eyJzY29wZWRQZXJtaXNzaW9uIjpbXSwicGVybWlzc2lvbnMiOlsiQS5hZG1pbl9jdXN0b21lcl9kZWxldGUiLCJBLm5vcm1hbF91c2VyX2FwcCIsIkEubm9ybWFsX3VzZXJfY29uZmlndXJhdGlvbiIsIkEubm9ybWFsX3VzZXJfd2VsY29tZV9jb250cm9scyIsIkEubm9ybWFsX3VzZXJfb3JkZXIiLCJBLm5vcm1hbF91c2VyX3NlYXJjaCIsIkEubm9ybWFsX3VzZXJfc2VhcmNoX3BjIiwiQS5ub3JtYWxfdXNlcl9zZWFyY2hfcHJpdmF0ZSIsIkEubm9ybWFsX3VzZXJfcHJpY2luZyIsIkEubm9ybWFsX3VzZXJfcHJpdmF0ZSIsIkEubm9ybWFsX3VzZXJfY29tbWVyY2lhbCIsIkEubm9ybWFsX3VzZXJfcGMiXSwibmFtZSI6WyJUZXN0Il0sIm1haWwiOlsiVGVzdEBleGFtcGxlLmNvbSJdLCJvcmdhbml6YXRpb24iOlsiWC1YeHh4eHguMTIzNCJdLCJsb2NhdGlvbiI6WyIxMjMyMSJdLCJ1bml0IjpbIjEwMyJdLCJjb3VudHJ5IjpbIkNOIl0sInVzZXJUeXBlIjoiZW1wbG95ZWUifSwiaWRlbnRpdHktaWQiOiJNb2NrIn0.EK5TbwsIgde3mT3n7NK2W7TCvpgQQLzshvPPANRQeUmKOv2AWbo_7vNEDTSkwUlaHRN3-dknv8F95p5MsGTzH6Uva8aOPJG6JdBIoYX_ud3aBN-hY1i2Xpf8pqjeINfY3_gDNAB9gdMznEej2uqhPwUXmZtcuWPdUCCeNqPJbRUAJeVXxLr_JtQzO2jmuwNY_YYp7KaEIANZwG1spvLuIGZ0HA03u8ye9c2lfqYcjgfIkjMrwgWPamR7joZOZPdQSO2EHrF7bUWMjRNY-FF5V7tOjEijkknE_nDq5THcEvx1seHYFdFNwy9LSSGGPVmZMKTKQ3UUlZZyBMXcOpOA9w`

I can commit the code successfully and gitleaks cannot detect such leaks.

**Expected behavior**
expect this jwt can be detected and commit should be blocked

**Basic Info (please complete the following information):**
 - OS: MAC OS
 - Gitleaks Version: v8.17.0

**Additional context**

cc @zricethezav

**Comment by rgmz** [comment]
Good catch, I've discovered a few valid JWTs that have not been caught by the current rule.

I think we ought to bump up the lengths for all sections:

1. The example header in [RFC 7519: Example JWT](https://datatracker.ietf.org/doc/html/rfc7519#section-3.1) is 40 characters long and would not be caught by `ey[0-9a-z]{30,34}\.`
2. I've found JWTs with large payloads, 500 characters may not suffice.
3. I've found JWTs with signatures almost 400 characters long

Additionally, the current rule is case-insensitive which increases the amount of false-positives, specifically around "ey" which should be a known discriminator.
