### ISSUE TITLE
secret detection wrong value

### ISSUE THREAD

**Issue by Madhukar-Fabrick** [gitleaks/gitleaks#1219]
**Describe the bug**
generic value detected as generic apikey(secret detection wrong/uuid value dectected as generic apikey)
**To Reproduce**
typescript
    `tokenizationId`: 'f865288c97ca4913887373728b8dfc4c',
the  code contains the above value and it is reported as : Generic API Key 

**Expected behavior**
this is not acutally Generic apikey so it should not detect as secret/it should skip

**Screenshots**
![image](https://github.com/gitleaks/gitleaks/assets/138442223/fd436c95-5437-4a92-9d77-c90506aebbf0)
![image](https://github.com/gitleaks/gitleaks/assets/138442223/93a7ff18-ec41-4302-a785-e1f05535f9d0)

**Basic Info (please complete the following information):**
 - OS: linux
 - Gitleaks Version:8.16.2

**Additional context**

cc @jamalunisha.u@centrico.tech

Regards,
Madhukar

**Comment by zricethezav** [comment]
What @gmsdelmundo said, the generic rule will inevitably have false positives. You can use your own configuration to tune the detection how you want
