### ISSUE TITLE
Last character being duplicated when running gitleaks detect on a custom configuration

### ISSUE THREAD

**Issue by gmsdelmundo** [gitleaks/gitleaks#1221]
**Describe the bug**

The last character in the "Finding" line of a secret gets duplicated.
e.g. mysecret-ABC -> mysecret-ABCC

**To Reproduce**

Running on Windows 11 using PowerShell.

Given a `test.txt` with the following text:
`mysecret-ABC`

And the following custom rule in `custom_gitleaks.toml`:
```
[[rules]]
id = "test"
description = "test"
regex = '''(mysecret-.*)'''
keywords = ["mysecret"]
secretGroup = 1
```

I run the following command:
`docker run -v C:\<path>\project:/path ghcr.io/gitleaks/gitleaks:latest detect --source="/path" -v --config="/path/custom_gitleaks.toml" --no-git`

And get the output:
```
Finding:     mysecret-ABCC
Secret:      mysecret-ABC
RuleID:      test
Entropy:     3.418296
File:        /path/test.txt
Line:        1
Fingerprint: /path/test.txt:test:1
```

**Expected behavior**

"Finding" should only show `mysecret-ABC`.

**Screenshots**

![image](https://github.com/gitleaks/gitleaks/assets/15458259/b8aefc43-425c-431d-9e90-fb1e3e980944)

**Basic Info (please complete the following information):**

 - OS: Windows 11 Version 10.0.22621 Build 22621
 - Gitleaks Version: Latest (v8.17.0 as of writing)

cc @zricethezav

**Comment by rgmz** [comment]
The issue is something to with how `finding` is assigned in `detect/utils.go#printFinding`:

https://github.com/gitleaks/gitleaks/blob/06db3b91d7495a39caf0d922aef5fee0118e7538/detect/utils.go#L148

**Comment by gmsdelmundo** [comment]
Ah yes, I was suspecting that there was something wrong in that function in `matchEnd` or `lineEnd`, but didn't have time to investigate deeper.

Since this is a problem with `lineEnd`, I suspect that there's an indexing issue between lines 131 and 136. I can take a look.

**Comment by gmsdelmundo** [comment]
Found the issue and raised a [PR](https://github.com/gitleaks/gitleaks/pull/1223).

```
                lineEndIdx := matchInLineIDX + len(f.Match)
                if len(f.Line)-1 <= lineEndIdx {
                        lineEndIdx = len(f.Line) - 1
                }
```
Essentially, if the match was found at the end of the line (or was the whole line itself), `lineEndIdx` was being assigned to the index of the last character of the line.

```
lineEnd := f.Line[lineEndIdx:]
```
Since `lineEndIdx` is now assigned as the index of the last character, `lineEnd` is therefore assigned as the last character itself, which duplicates the last character of the secret value.

Thus, the fix here would be to set `lineEndIdx` to be after the index of the last character, i.e. update the `lineEndIdx` assignment in the if-condition:
```
                lineEndIdx := matchInLineIDX + len(f.Match)
                if len(f.Line)-1 <= lineEndIdx {
                        lineEndIdx = len(f.Line)
                }
```
