### ISSUE TITLE
#gitleaks:allow doesnt work properly

### ISSUE THREAD

**Issue by kuznas** [gitleaks/gitleaks#1245]
**Describe the bug**
I have gitlab project, where intentionally hardcoded some tokens. I've added comment #gitleaks:allow (as you can see on screenshots) and unfortunatelly nothing changed, this token still being detected by gitleaks in my pipeline

**To Reproduce**
add #gitleaks:allow after any secret in your file

**Expected behavior**
Token is absent from report

**Screenshots**
![gitleaks-allow](https://github.com/gitleaks/gitleaks/assets/82405506/fec92d63-eb7c-4b4e-9858-15241cbc5e34)

![pipeline](https://github.com/gitleaks/gitleaks/assets/82405506/94247c53-dad9-4135-8291-65068168b274)

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:  v8.17.0

**Comment by zricethezav** [comment]
What type of scan? `gitleaks:allow` does not ignore secrets that have been previously committed

**Comment by kuznas** [comment]
so, gitleaks:allow works only for the first commit?
How can I exclude from scan already commited secrets without using .gitleaksignore?
im asking due to the fact, that in .gitleaksignore i have to mention commit/file/type/line
as it shown here: 
418edf165dbb63d6f46993ae8f8818ffd87ea582:cmd/generate/config/rules/jwt.go:jwt:17
but the difficulty in this case that code changes ang line can change many times, it means that every time developers should change lines in .gitleaksignore too, thats why idea using #gitleaks:allow seems to me very interesting. Maybe you have any advices to my case? i use gitleaks in my ci/cd pipelines as an additional stage before build.

**Comment by zricethezav** [comment]
you gotta use either a .gitleaksignore file or configure your gitleaks.toml with an allowlist to ignore the secret based on a regex. 

`gitleaks:allow` primary use case is for committing secrets that are either for tests or known false positives

**Comment by kuznas** [comment]
Thank you @zricethezav
