### ISSUE TITLE
False positives of "stripe-access-token" rule

### ISSUE THREAD

**Issue by MarekSven** [gitleaks/gitleaks#1276]
**Describe the bug**
The regex of the stripe-access-token rule matches more that it probably should.

**To Reproduce**
Try to match the following innocent test names, e.g. on regex101.com:
- calculation_task_test_construction
- calculation_task_test_100012345678

**Expected behavior**
The above mentioned test names do not match.

I am not an regex expert, but the current regex of the rule:
```
(?i)(sk|pk)_(test|live)_[0-9a-z]{10,32}
``` 

might be modified e.g. to:
```
(?i)(^|[^0-9a-z])(sk|pk)_(test|live)_[0-9a-z]{10,32}
```

**Screenshots**

Current regex matches:
![image](https://github.com/gitleaks/gitleaks/assets/33157476/d734a457-0ecc-4e67-8881-9f68e5682c09)

Proposed regex matches:
![image](https://github.com/gitleaks/gitleaks/assets/33157476/46fa614f-4de9-4ed7-bacb-83e526fd59e5)

cc @zricethezav

**Comment by rgmz** [comment]
The generateUniqueTokenRegex helper would probably fix this.

https://github.com/gitleaks/gitleaks/blob/6d0d8b5068153013722608ac6a8bb5c388d68bc4/cmd/generate/config/rules/openai.go#L13
