### ISSUE TITLE
gitleaks still scanning node_modules and dist folder even ignoring them in gitleaks.toml in docker mode

### ISSUE THREAD

**Issue by JanPalach82** [gitleaks/gitleaks#1286]
**Describe the bug**
Hello dear friends!
My name is Jan Palach. I am facing an weird issue with gitleaks in docker mode. While using it in native executable mode nothing wrong seems to happen. The problem is, while running in docker mapping the target project to scan, gitleaks tell us that it has found the config file,but it still scanning node_modules and dist folders tooking to long to finish because my node_modules is huge. 

**To Reproduce**
1 - Follow the docker mode from the documentation
2 - put the following configfile  in a path mapped path to expose to the docker image:
`title = "Gitleaks Config File"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
paths = [
    '''.gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe)$''',
    '''(go.mod|go.sum)$''',
    '''gradle.lockfile''',
    '''yarn.lock''',
    '''package-lock.json''',
    '''package.json''',
    '''pnpm-lock.yaml''',
    '''Database.refactorlog''',
    '''vendor''',
    '''.*.test.*''',
    '''.*.swagger.*''',
    '''.*.error.*''',
    '''docs''',
    '''errors''',
    '''messages''',
    '''gitleaks_findings.json''',
    '''pre-commit''',
    '''README.md''',
    '''dist''',
    '''node_modules'''
]
`
3 - Then run the docker image pointing to the config file listed above:
docker run -v project root path:/app zricethezav/gitleaks:latest detect -l debug --no-git --source /app --verbose --no-banner --redact --config=/app/devsecops-secrets-detection/.gitleaks.toml

Result:
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
2:48PM DBG using gitleaks config /app/devsecops-secrets-detection/.gitleaks.toml from `--config`
2:48PM DBG extending config with default config
**2:50PM INF scan completed in 1m51s**
2:50PM WRN leaks found: 1
Finding:     const fooAwsSecret = "REDACTED"
Secret:      REDACTED
RuleID:      aws-access-token
Entropy:     3.646439
File:       foofile
Line:        68
Fingerprint:foofile:aws-access-token:68

**Expected behavior**
It sholud run ignoring node_modules and dist paths, but it does not. Removing these paths the docker image runs the application in an expected time window.

**Basic Info (please complete the following information):**
 - OS: MacOS
 - Gitleaks Version: Latest docker image 8.18.0

I do really appreciate your attention my friends!

cc @zricethezav

**Comment by JanPalach82** [comment]
For a while, I've just mounted both node_modules and dist directory as anonymous ones and it runs perfectly. But I guess this is just an workaround..

**Comment by zricethezav** [comment]
@JanPalach82 thanks for opening this issue. I'll try to investigate. I think there are some other issues with regard to running in docker mode that might provide some helpful context

**Comment by huornlmj** [comment]
Same issue here.

.gitleaks.toml
```
[allowlist]
  paths = ['''tests''']
```
Command:
```console
$ docker run -v $PWD:/path zricethezav/gitleaks:latest detect --source="/path" -v
```

**Comment by jschaf** [comment]
I'm trying to add gitleaks but can't figure out how to skip node_modules. I'm running gitleaks directly:

### version

```
gitleaks --version
gitleaks version 8.21.2
```

### gitleaks.toml
```toml
[extend]
useDefault = true

[allowlist]
description = "allowlist"

paths = [
  '''^node_modules/''',
]
```

### Output

```bash
gitleaks dir --no-banner --config=gitleaks.toml --log-level=debug .

Output
5:03PM DBG using gitleaks config dev/lint/gitleaks/gitleaks.toml from `--config`
5:03PM DBG extending config with default config
5:03PM DBG Skipping symlink path=node_modules/.pnpm/@ag-grid-community+client-side-row-model@32.2.0/node_modules/@ag-grid-community/core
5:03PM DBG Skipping symlink path=node_modules/.pnpm/@ag-grid-community+client-side-row-model@32.2.0/node_modules/tslib
5:03PM DBG Skipping symlink path=node_modules/.pnpm/@ag-grid-community+core@32.2.0/node_modules/ag-charts-types
```

### Hypothesis

It looks like gitleaks descends into directories that match the allowlist instead of bailing early. If this is the problem, it's analogous to the find `-path` and `-prune` options. A common mistake with `find` is to filter out paths instead of pruning to avoid scanning directories.

**Comment by jschaf** [comment]
Interestingly, passing a single file works. However, passing two or more files causes gitleaks to scan everything.

**Comment by rgmz** [comment]
> ### Hypothesis
> 
> It looks like gitleaks descends into directories that match the allowlist instead of bailing early. If this is the problem, it's analogous to the find `-path` and `-prune` options. A common mistake with `find` is to filter out paths instead of pruning to avoid scanning directories.

You're right — and this makes sense considering the logic was likely written to receive arbitrary paths from `git log`.

The [`dir` command walks the entire tree](https://github.com/gitleaks/gitleaks/blob/master/sources/directory.go) and [sends all files over a channel](https://github.com/gitleaks/gitleaks/blob/7f77987d91c590e021d9fa2b3c0e57c4a4376147/detect/directory.go#L76).

The `paths` allowlist currently isn't tested until after the file is read and passed to the `Detect` function.

https://github.com/gitleaks/gitleaks/blob/7f77987d91c590e021d9fa2b3c0e57c4a4376147/detect/detect.go#L176-L182

**Comment by rgmz** [comment]
I've opened #1653 to fix this.

+ @zricethezav
