### ISSUE TITLE
Style: Sort the stopwords for better debugging in config

### ISSUE THREAD

**Issue by nnungest** [gitleaks/gitleaks#1290]
**Is your feature request related to a problem? Please describe.**
I cant live in a world where things are left to chaos.

**Describe the solution you'd like**
Just alpha sort... visual select | gnu sort

**Describe alternatives you've considered**
Live in a state of denial.

**Additional context**
Yeah... here is the pr https://github.com/gitleaks/gitleaks/pull/1289
cc @zricethezav

**Comment by nnungest-aca** [comment]
this has been resolved with https://github.com/gitleaks/gitleaks/pull/1289 . closing the issue as completed
