### ISSUE TITLE
`hashicorp-tf-password` rule seems to be too wide

### ISSUE THREAD

**Issue by Coruscant11** [gitleaks/gitleaks#1302]
**Describe the bug**
While scanning a tons of repositories recently, I have the feeling that the `hashicorp-tf-password` in Gitleaks seems to be a huge source of false positive. It raises findings that were usually avoided by gitleaks (with entropy mechanisms etc).

**To Reproduce**
Texts with the `password` stopword

**Expected behavior**
These kind of matches should be handled by the `generic-api-key` rule, or at least one of the built-in rules.

**Screenshots**
![Screenshot_20231127_120857](https://github.com/gitleaks/gitleaks/assets/1645347/43a529ef-365a-49e6-91a6-37fbe2b2e9a6)

**Basic Info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Gitleaks Version:  8.18.0

**Additional context**
Maybe we could bind the rule to a specific file extension ?

cc @zricethezav

**Comment by echoix** [comment]
I agree, I stumbled on this issue when looking at why I got detections for hashicorp-tf-password on a repo that would enable gitleaks for the first time. All issues were in documentation example strings, just like here

**Comment by bgardner-noggin** [comment]
I also agree that this seems a little silly. This is being picked up in nearly all of our pipelines now.

It is fairly common to have test files which have a password set to "password"
