### ISSUE TITLE
gitleaks detect consistently reports wrong commit information for some secrets

### ISSUE THREAD

**Issue by nicholas-arnica** [gitleaks/gitleaks#1333]
**Describe the bug**
`gitleaks detect` consistently reports the wrong commit information (`Commit`, `Author`, `Email`, `Date`, `Message`) for many findings.

The `StartLine`, `EndLine`, `StartColumn`, `EndColumn`, `Match`, `Secret`, and `File` are all correct.

We've observed this across several unrelated repositories.

(speculation) It looks like there may be a bug with parsing the `git log`s, as the `Message` field looks like it's appending git log information from the CORRECT commit. For example, in the example below, the commit message `gitleaks detect` reports is:

```
Merge branch 'BLAKE3' of github.com:BoloniniD/ClickHouse into BLAKE3

commit 645e156af6b362145fad82d714f8e70a5b5a55a8
Author: Meena Renganathan <Meena.Renganathan@ibm.com>
Date:   Wed Apr 6 14:50:10 2022 -0700

Updated the boringssl-cmake to match the latest broingssl module update
```

but the message for `f6ded7a51cf917bdb44097066fab608c0facde5b` is just
```
Merge branch 'BLAKE3' of github.com:BoloniniD/ClickHouse into BLAKE3
```

but if we `git log 645e156af6b362145fad82d714f8e70a5b5a55a8` (id taken from the "leaked" Message), we have:
```
commit 645e156af6b362145fad82d714f8e70a5b5a55a8
Author: Meena Renganathan <Meena.Renganathan@ibm.com>
Date:   Wed Apr 6 14:50:10 2022 -0700

    Updated the boringssl-cmake to match the latest broingssl module update
```

**To Reproduce**
1) Clone https://github.com/nicholas-gitgoat/ClickHouse
2) Run `gitleaks detect -r gitleaks.json`

Should have output similar to below
```
9:00AM WRN warning: exhaustive rename detection was skipped due to too many files.
9:00AM WRN warning: you may want to set your diff.renameLimit variable to at least 1128 and retry the command.
9:00AM INF 74007 commits scanned.
9:00AM INF scan completed in 2m5s
9:00AM WRN leaks found: 849
```

Edit: Use `gitleaks detect -s /home/nicholas/Projects/ClickHouse/ -r gitleaks.json --log-opts="^645e156af6^ 645e156af6 f6ded7a51cf917bdb44097066fab608c0facde5b"` for a quicker scan that doesn't take 2 minutes, and also reproduces the issue

3) Open `gitleaks.json` and search for the Fingerprint `f6ded7a51cf917bdb44097066fab608c0facde5b:contrib/boringssl-cmake/crypto_test_data.cc:generic-api-key:2897`

```json
{
  "Description": "Generic API Key",
  "StartLine": 2897,
  "EndLine": 2897,
  "StartColumn": 8277,
  "EndColumn": 8326,
  "Match": "key.y = 1e77f842b1ae0fcd9929d394161d41e14614ff750\"",
  "Secret": "1e77f842b1ae0fcd9929d394161d41e14614ff750",
  "File": "contrib/boringssl-cmake/crypto_test_data.cc",
  "SymlinkFile": "",
  "Commit": "f6ded7a51cf917bdb44097066fab608c0facde5b",
  "Entropy": 3.7105815,
  "Author": "BoloniniD",
  "Email": "denis@bolonin.ru",
  "Date": "2022-04-06T22:07:38Z",
  "Message": "Merge branch 'BLAKE3' of github.com:BoloniniD/ClickHouse into BLAKE3\n\ncommit 645e156af6b362145fad82d714f8e70a5b5a55a8\nAuthor: Meena Renganathan \u003cMeena.Renganathan@ibm.com\u003e\nDate:   Wed Apr 6 14:50:10 2022 -0700\n\nUpdated the boringssl-cmake to match the latest broingssl module update",
  "Tags": [],
  "RuleID": "generic-api-key",
  "Fingerprint": "f6ded7a51cf917bdb44097066fab608c0facde5b:contrib/boringssl-cmake/crypto_test_data.cc:generic-api-key:2897"
}
```

4) Open `f6ded7a51cf917bdb44097066fab608c0facde5b:contrib/boringssl-cmake/crypto_test_data.cc` and search for `key.y = 1e77f842b1ae0fcd9929d394161d41e14614ff750"`
4a) You can do `git show f6ded7a51cf917bdb44097066fab608c0facde5b:contrib/boringssl-cmake/crypto_test_data.cc` and in `less` use `/key.y = 1e77f842b1ae0fcd9929d394161d41e14614ff750"` to search.

You will get no results.

5) If you go to the specified `StartLine` (2897), you will find an empty line:
```
2896 static const size_t kLen57 = 465;
2897 
2898 static const char *kData57[] = {
```

**Expected behavior**
Instead, for this specific finding, we would expect it to report `Commit: "645e156af6b362145fad82d714f8e70a5b5a55a8"`

Using that commit id, and looking in that file (`git show 645e156af6b362145fad82d714f8e70a5b5a55a8:contrib/boringssl-cmake/crypto_test_data.cc`) we find the exact `Match`, exactly where it's supposed to be.

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Xubuntu 23.10 (Linux 6.5.0-15-generic)
 - Gitleaks Version: 8.16.0-1ubuntu0.1

**Additional context**
You can find each instance of it reporting the wrong commit in a gitleaks report by searching for `\n\ncommit`.

cc @zricethezav

**Comment by nicholas-arnica** [comment]
It MIGHT be related to #1028, but I have confirmed: in the example I provide above, the secret was introduced in `645e156af6b362145fad82d714f8e70a5b5a55a8`, which is not a merge commit.

![image](https://github.com/gitleaks/gitleaks/assets/130402784/f43463fa-9ef2-46bb-bdb4-041c0291e394)

**Comment by nicholas-arnica** [comment]
Okay, it's a similar but different issue from #1028.

The issue is that the header being returned is:

```
commit f6ded7a51cf917bdb44097066fab608c0facde5b
Merge: b2cf1cd0de 0254477421
Author: BoloniniD <denis@bolonin.ru>
Date:   Thu Apr 7 01:07:38 2022 +0300

    Merge branch 'BLAKE3' of github.com:BoloniniD/ClickHouse into BLAKE3

commit 645e156af6b362145fad82d714f8e70a5b5a55a8
Author: Meena Renganathan <Meena.Renganathan@ibm.com>
Date:   Wed Apr 6 14:50:10 2022 -0700

    Updated the boringssl-cmake to match the latest broingssl module update
```

So, all the diffs for `645e156af6b362145fad82d714f8e70a5b5a55a8` are being attributed to `f6ded7a51cf917bdb44097066fab608c0facde5b`.

I fix will have to be made to https://github.com/gitleaks/go-gitdiff

**Comment by zricethezav** [comment]
Hi @nicholas-arnica,

Thank you for opening this issue an providing plenty of detail, especially instructions on reproducing the behavior. This is truly a rockstar issue right here.

I'll start digging into this issue this week.

**Comment by egorbeliy** [comment]
hi everyone, do you know the workaround for it?

**Comment by rgmz** [comment]
Another example that I stumbled upon. (Wasn't there another issue for this that I commented in?

The reported path doesn't exist in `7815ce1d3197c4cd18d7a3b3aaf09d6fd22b278b`.

**Finding**
```
Finding:     kind: Secret            
metadata:               
  name: environment     
  namespace: kube-system
type: Opaque            
data:                   
                        elasticsearch-password: Y2hhbmdlbWU=
Secret:      elasticsearch-password: Y2hhbmdlbWU=
RuleID:      kubernetes-secret-yaml
Entropy:     4.350209
File:        cluster/addons/fluentd-elasticsearch/env-secret.yaml
Line:        2
Commit:      84e0326eb1f108f0d7aa2e9e48fb0c4a8edb4bd5
Author:      Kubernetes Submit Queue
Email:       k8s-merge-robot@users.noreply.github.com
Date:        2017-08-02T19:46:57Z
Fingerprint: 84e0326eb1f108f0d7aa2e9e48fb0c4a8edb4bd5:cluster/addons/fluentd-elasticsearch/env-secret.yaml:kubernetes-secret-yaml:2
```

**Commit Log**
```
commit 7815ce1d3197c4cd18d7a3b3aaf09d6fd22b278b
Merge: 64a984bb626 be747993585
Author: Kubernetes Submit Queue <k8s-merge-robot@users.noreply.github.com>
Date:   Wed Aug 2 12:03:42 2017 -0700

    Merge pull request #50029 from cblecker/cblecker-hack-owners
    
    Automatic merge from submit-queue
    
    Add cblecker to hack/ owners
    
    This PR adds myself to the approvers list for `hack/`. I've been helping do a bunch of improvements here over the past few months, and want to continue doing so.
    
    I solemnly promise to use approval powers for good, and only approve things that I know are safe and within my area of expertise!
    
    ```release-note
    NONE
    ```
    /cc @ixdy @sttts @fejta @spxtr

commit 0ed0f02c7622ee2403992560ae00b10ab3bcb6ee
Author: Arve Knudsen <arve.knudsen@gmail.com>
Date:   Mon Jul 10 20:09:29 2017 +0200

    Upgrade Elasticsearch/Kibana to 5.5.1 and use official Kibana image

diff --git a/cluster/addons/fluentd-elasticsearch/env-secret.yaml b/cluster/addons/fluentd-elasticsearch/env-secret.yaml
new file mode 100644
index 00000000000..9e045135463
--- /dev/null
+++ b/cluster/addons/fluentd-elasticsearch/env-secret.yaml
@@ -0,0 +1,8 @@
+apiVersion: v1
+kind: Secret
+metadata:
+  name: environment
+  namespace: kube-system
+type: Opaque
+data:
+  elasticsearch-password: Y2hhbmdlbWU=
```
