### ISSUE TITLE
Finding sometimes is incorrectly reported to span multiple lines

### ISSUE THREAD

**Issue by m1cm1c** [gitleaks/gitleaks#1352]
**Describe the bug**
Sometimes, the reported start and end lines are different even though the end line has nothing to do with the finding

**To Reproduce**
1. Create a new directory containing only a single file (`.env.prod`) with the following content:
```
DB_HOST=example.com
DB_PORT=443
DB_USERNAME=postgres
DB_PASSWORD=8ae31cacf141669ddfb5da
DB_NAME=best_db
DB_SSL=true
```
2. Run `gitleaks detect --no-git --report-path o`
3. In `o` , you will find the following report:
```
[
 {
  "Description": "Detected a Generic API Key, potentially exposing access to various services and sensitive operations.",
  "StartLine": 4,
  "EndLine": 5,
  "StartColumn": 5,
  "EndColumn": 1,
  "Match": "PASSWORD=8ae31cacf141669ddfb5da",
  "Secret": "8ae31cacf141669ddfb5da",
  "File": ".env.prod",
  "SymlinkFile": "",
  "Commit": "",
  "Entropy": 3.5383105,
  "Author": "",
  "Email": "",
  "Date": "",
  "Message": "",
  "Tags": [],
  "RuleID": "generic-api-key",
  "Fingerprint": ".env.prod:generic-api-key:4"
 }
]
```

**Expected behavior**
The start line is correct. However, the start column already is wrong because start column 5 means that the finding is

```
SSWORD=8ae31cacf141669ddfb5da
DB
```

if columns are 0-indexed and

```
ASSWORD=8ae31cacf141669ddfb5da
D
```

if columns are 1-indexed.

However, what really seems very wrong is the jump into line 5 because `DB_NAME` has nothing to do with the password.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: Manjaro
 - Gitleaks Version: 8.18.2

cc @zricethezav

**Comment by zricethezav** [comment]
@m1cm1c thanks for raising this issue. I'm able to reproduce it but don't have a solution right now. If a community member wants to investigate that would be great, if not, then I'll get to it eventually.

**Comment by recreator66** [comment]
@m1cm1c  @zricethezav  I would like to support you with fixing this issue.

I assume that the jump from “Startline” to “Endline” is caused by the regex pattern of the “generic-api-key” rule scanning for newlines and any whitespace.

However, I will verfiy this and check why the "StartColumn" is set incorrectly.

**Comment by recreator66** [comment]
sorry for messing up this issue with a deleted PR, I am actually used to GitLab, shame on me 😄 

_Here is what I found out so far:_

I was able to reproduce this bug not only for the generic-api-key rule. All rules that follow the default [secretSuffix](https://github.com/gitleaks/gitleaks/blob/4e43d1109303568509596ef5ef576fbdc0509891/cmd/generate/config/utils/generate.go#L30) are affected. I hope that I will be able to fix this during this weekend. Here another example:
```
TEST_TEST=first_test
TEST_FLICKR=anbcbajkl123451414414acvderwe213
TEST_NEW_TEST=second_test
TEST_NAME=test_name
```

result:

```json
[
  {
    "Description": "Discovered a Flickr Access Token, posing a risk of unauthorized photo management and potential data leakage.",
    "StartLine": 2,
    "EndLine": 3,
    "StartColumn": 7,
    "EndColumn": 1,
    "Match": "FLICKR=anbcbajkl123451414414acvderwe213",
    "Secret": "anbcbajkl123451414414acvderwe213",
    "File": "env.prod2",
    "SymlinkFile": "",
    "Commit": "",
    "Entropy": 3.8133073,
    "Author": "",
    "Email": "",
    "Date": "",
    "Message": "",
    "Tags": [],
    "RuleID": "flickr-access-token",
    "Fingerprint": "env.prod2:flickr-access-token:2"
   }
]
```

@m1cm1c gitleaks is actually not reporting the wrong start column. Let's take your example:

`DB_PASSWORD=8ae31cacf141669ddfb5da`

Here gitleaks detects the regex match at column 5, which means P is at index 5. Take into consideration that it starts counting at 1, that's the reason why EndColumn is in your example also correct.
