### ISSUE TITLE
Add a Type field into report.Finding struct

### ISSUE THREAD

**Issue by ebarped** [gitleaks/gitleaks#1360]
**Is your feature request related to a problem? Please describe.**
I was using this excellent tool to generate a report about my leaks. I was using the Description field to show the type of leak, but with the merged https://github.com/gitleaks/gitleaks/pull/1300 into 8.18.2, my report changed from:

| type           | file      |   
|----------------|-----------|
| JSON Web Token | myfile.go |  

to

| type                                                                                                                         | file      |   
|------------------------------------------------------------------------------------------------------------------------------|-----------|
| Uncovered a JSON Web Token, which may lead to unauthorized access to web applications and sensitive user data. | myfile.go |   |   |   

**Describe the solution you'd like**
I would like to add a new field, something like **Type**, that uses the old description data in v8.18.1 and previous, so we could generate reports like:

| type           | description                                                                                                    | file      |
|----------------|----------------------------------------------------------------------------------------------------------------|-----------|
| JSON Web Token | Uncovered a JSON Web Token, which may lead to unauthorized access to web applications and sensitive user data. | myfile.go |

**Additional context**
I am willing to work on this, but i need to know if this would be a nice feature and if it will be accepted.

cc @zricethezav

**Comment by ebarped** [comment]
I think that this issue is related to https://github.com/gitleaks/gitleaks/issues/1362

**Comment by ebarped** [comment]
I think that this issue is not solved by #1473. I am proposing to add another field to `report/finding.go` struct (https://github.com/gitleaks/gitleaks/blob/master/report/finding.go#L10), maybe named `Type` or `ShortDescription`, which value is the value of the field `Description` before the merge of #1300.

So, in the end, a Finding will have the fields:
- Description: `Detected a Generic API Key, potentially exposing access to various services and sensitive operations.`
- Type/ShortDescription: `Generic API Key`

**Comment by rgmz** [comment]
> I was using the Description field to show the type of leak, but with the merged https://github.com/gitleaks/gitleaks/pull/1300 into 8.18.2, my report changed from:

Can you elaborate on what "[your] report" entails? Are you ingesting the SARIF data into GitHub or something similar?

----

I believe the impetus for #1300 was that the descriptions were redundant/low-value. While a human-readable name like "Generic API Key" is nice, I don't think something like "generic-api-key" is much worse.

IMO the problem is maintenance, both for the core Gitleaks ruleset and any custom configs people may build. Personally, I _almost never_ use the description field in my custom ruleset as I don't see a point — I would bet a lot of people are like this. Thus, to have an optional "type" field, in addition to "description", seems questionable when neither are likely to be used.

**Comment by ebarped** [comment]
I probably explained myself wrong, sorry!

Im using gitleaks as a library, importing it from my own go code: i scan a bunch of repositories and generate a report with info about the secrets detected on each one.

So, before #1300, the report looked clean, i only want to know what type of secret it detected, not the full description. After #1300, i can no longer specify the type of secret, only the description. I can do a workaround using the `RuleID` field, but its not so clean.

So, im wondering if it makes sense to add again the old description, but in a new field, like `Type` or `ShortDescription` to the `Finding` struct.

Thanks anyway!
