### ISSUE TITLE
rep-receive hook at Github enterprise

### ISSUE THREAD

**Issue by roshvin** [gitleaks/gitleaks#1368]
**Is your feature request related to a problem? Please describe.**

Hi , we are testing Gitleaks at Github Enterprise & not able to find steps / docs , could you please help to get some pointers.

Thanks 

cc @zricethezav

**Comment by zricethezav** [comment]
@roshvin Unfortunately, I don't support a pre-receive hook. There may be some work around solutions buried in the issues: https://github.com/gitleaks/gitleaks/issues/821.

**Comment by zricethezav** [comment]
Closing this issue as I don't have the bandwidth to support this feature
