### ISSUE TITLE
Output information for fingerprints in .gitleaksignore which does not fit to the scan.

### ISSUE THREAD

**Issue by AnselmD** [gitleaks/gitleaks#1398]
**Is your feature request related to a problem? Please describe.**
Sometimes the fingerprints in .gitleaksignore are outdated or wrong and does not fit to the result of the scan. This can happen with a git squashed merge. 

**Describe the solution you'd like**
I would like to have information about those fingerprints in .gitleaksignore which are not found in the scan.

**Describe alternatives you've considered**
n.a.

cc @zricethezav

**Comment by zricethezav** [comment]
@AnselmD I designed the fingerprint system in a way that was append-only. If you wanted to remove outdated fingerprints due to git squashes then you'll have to do that manually
