### ISSUE TITLE
Add missing GitLab token patterns

### ISSUE THREAD

**Issue by bgoareguer** [gitleaks/gitleaks#1401]
Some Gitlab tokens are not detected by Gitleaks (e.g. Deploy token, CI/CD Job token, Feed token, etc.). The complete list of Gitlab token prefixes can be found [here](https://docs.gitlab.com/ee/security/token_overview.html#token-prefixes):

![image](https://github.com/gitleaks/gitleaks/assets/43874676/ce2bb082-85e1-437b-84cd-f21a289124b6)

cc @zricethezav

**Comment by bufferoverflow** [comment]
new URL https://docs.gitlab.com/ee/security/tokens/index.html#token-prefixes

also relevant:
- https://gitlab.com/gitlab-org/security-products/secret-detection/secret-detection-service/-/blob/main/lib/gitlab/secret_detection/core/gitleaks.toml?ref_type=heads
- https://gitlab.com/gitlab-org/security-products/secret-detection/secret-detection-rules/-/blob/main/rules/mit/gitlab.toml?ref_type=heads
