### ISSUE TITLE
Make from source: directions wrong

### ISSUE THREAD

**Issue by p1r473** [gitleaks/gitleaks#1412]
**Describe the bug**
Error when trying to make from source
```
go fmt ./...
make: go: No such file or directory
make: *** [Makefile:13: format] Error 127 
```

**To Reproduce**
```
git clone https://github.com/gitleaks/gitleaks.git
cd gitleaks
make build
```

**Expected behavior**
Build should succeed

**Screenshots**
![image](https://github.com/gitleaks/gitleaks/assets/9235633/bf63f4a9-89dc-4c48-8d88-18c76a807388)

**Basic Info (please complete the following information):**
 - OS: Debian BOokworm
 - Gitleaks Version: 8.18.2

**Additional context**

cc @zricethezav

**Comment by dcostersabin** [comment]
Is go installed in your system ? 

![image](https://github.com/gitleaks/gitleaks/assets/29281005/d02034da-3ad7-43f0-b1e4-b598703a47e2)

**Comment by zricethezav** [comment]
@p1r473 looks like you don't have go installed. I updated the readme to add a comment for installing go

**Comment by p1r473** [comment]
Yep thanks! That was it
