### ISSUE TITLE
gitleaks detect missing one commit in scan

### ISSUE THREAD

**Issue by edishu** [gitleaks/gitleaks#1414]
**Describe the bug**
When I use `gitleaks detect .`, locally in my repo, one commit is omitted from scanning.
My repo's main branch has 67 commits while gitleaks scans only 66 commits.

**To Reproduce**
I'm not sure how to reproduce this.

**Expected behavior**
`gitleaks detect` command should scan all the commits on all branches

**Screenshots**
<img width="450" alt="image" src="https://github.com/gitleaks/gitleaks/assets/37514088/703854e0-3120-43bb-bc48-55607981accd">

**Basic Info (please complete the following information):**
 - OS: macOS 14.4.1
 - Gitleaks Version: 8.18.2

cc @zricethezav

**Comment by zricethezav** [comment]
You likely have a commit with just deletions. Commits with just deletions are not counted. This is known behavior and there is a `--log-level=debug` message for it

**Comment by edishu** [comment]
> --log-level=debug



> You likely have a commit with just deletions. Commits with just deletions are not counted. This is known behavior and there is a `--log-level=debug` message for it

sounds good, thanks for clarification!
