### ISSUE TITLE
secrets mistaken as Terraform passwords

### ISSUE THREAD

**Issue by elchenberg** [gitleaks/gitleaks#1418]
**Describe the bug**

When I scan a directory that does not contain any Terraform files I still get `hashicorp-tf-password` findings.

**To Reproduce**

1. Use Gitleaks version 8.18.3.
2. Have a directory with the following `auth.json` file:

    ```json
    {
      "http-basic": {
        "github.com": {
          "username": "redacted-username",
          "password": "bE5ejpYrEoKwJzeHryx4"
        }
      }
    }
    ```

    Output of `gitleaks detect --verbose --no-color --no-git`:

    ```
    Finding:     password": "bE5ejpYrEoKwJzeHryx4"
    Secret:      "bE5ejpYrEoKwJzeHryx4"
    RuleID:      hashicorp-tf-password
    Entropy:     4.095795
    File:        auth.json
    Line:        5
    Fingerprint: auth.json:hashicorp-tf-password:5
    ```

**Expected behavior**

Expected output:

```
Finding:     password": "bE5ejpYrEoKwJzeHryx4"
Secret:      bE5ejpYrEoKwJzeHryx4
RuleID:      generic-api-key
Entropy:     4.021928
File:        auth.json
Line:        5
Fingerprint: auth.json:generic-api-key:5
```

**Basic Info (please complete the following information):**
 - OS: Linux x64
 - Gitleaks Version: 8.18.3

**Additional context**

I got the expected output when I extended the "hashicorp-tf-password" rule in my `.gitleaks.toml`:

```toml
[[rules]]
id = "hashicorp-tf-password"
path = '''\.tf$'''
```

Maybe a similar path restriction can be added to the rule in [config/gitleaks.toml](https://github.com/gitleaks/gitleaks/blob/v8.18.3/config/gitleaks.toml#L2105).

**Comment by zricethezav** [comment]
Thanks for opening this issue @elchenberg. @becojo graciously opened a PR that was merged that should fix this https://github.com/gitleaks/gitleaks/pull/1420. We could probably tune the regex a little more too. Closing this issue for now.
