### ISSUE TITLE
Add gradles verification-metadata.xml to the global allowlist

### ISSUE THREAD

**Issue by niklas-w7** [gitleaks/gitleaks#1445]
**Is your feature request related to a problem? Please describe.**
Using gitleaks for a gradle based project it reports false positive leaks for gradles generated verification-metadata.xml file.
Also see https://docs.gradle.org/current/userguide/dependency_verification.html

**Describe the solution you'd like**
Add the file to the global allowlist.

cc @zricethezav

**Comment by PascalTurbo** [comment]
+1
