### ISSUE TITLE
Invalid --log-opts disregards git log exit code and silently does nothing at all

### ISSUE THREAD

**Issue by mriehl** [gitleaks/gitleaks#1450]
**Describe the bug**

Gitleaks doesn't seem to consider the git log exit code. When `--log-opts` is set to an invalid value, gitleaks will echo the stderr message but [exit with 0 and claim no leaks were found](https://github.com/gitleaks/gitleaks/blob/master/cmd/detect.go#L90). This is fatal in automated scenarios like CI or precommit hook because users must now rely on spotting the output instead of reacting to the process exit code which is what automation relies on to detect failures.
If gitleaks can't get a valid git log, the entire scan is compromitted and should report an error IMO.

Note: fixing this issue will probably also affect running `gitleaks detect` in a `cwd` that is not a git repository since for some reason this also does `exit 0` despite not scanning anything.

**To Reproduce**

```bash
gitleaks detect --log-opts=--invalid
```

**Expected behavior**
Exit 1, because `git log --invalid` doesn't work and exits with code 128.
It would be fine if there was a `--fail-on-git-error` option or similar, similar to the way curl handles status errors. This would preserve existing behaviour and users that rely on it while allowing automation around gitleaks to become more robust.

**Screenshots**

```bash
» gitleaks detect --log-opts=--invalid

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

7:03AM ERR [git] fatal: unrecognized argument: --invalid
7:03AM ERR  error="stderr is not empty"
7:03AM INF scan completed in 37ms
7:03AM INF no leaks found

» echo $?
0
```

**Basic Info (please complete the following information):**
 - OS: OSX
 - Gitleaks Version: 8.18.4

**Additional context**

- In technical terms the issue is that `detector.DetectGit` replaces the previous `err` with `nil` by scanning zero files, which succeeds trivially.
- If we agree on how gitleaks should behave and it helps move things forward, I'm open to creating a pull request to adjust behaviour

cc @zricethezav

**Comment by rgmz** [comment]
It _may_ be a bug that `err` shadows the variable from the outer scope.

https://github.com/gitleaks/gitleaks/blob/0334ec10760314034822710507631d0f6d3acecb/cmd/detect.go#L88

This results in `findingSummaryAndExit` always receiving `nil`.
https://github.com/gitleaks/gitleaks/blob/0334ec10760314034822710507631d0f6d3acecb/cmd/detect.go#L99
