### ISSUE TITLE
Should you use --mirror argument when scanning a repository for secrets

### ISSUE THREAD

**Issue by g3kk0** [gitleaks/gitleaks#1452]
Is it considered best practice to use the `--mirror` option when cloning a repository prior to scanning it for secrets?

The reason I ask is I've just detected secrets on one of my projects that only appear when the repository is cloned using the `--mirror` argument.

When I lookup the commit in question GitHub shows this warning "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

After some searching online I also came across this https://wwws.nightwatchcybersecurity.com/2022/02/11/gitbleed/

**Comment by rgmz** [comment]
Yes. Using --mirror will include refs from the remote that aren't included with a normal clone.
