### ISSUE TITLE
Scan for broken git repo

### ISSUE THREAD

**Issue by hvprvtr** [gitleaks/gitleaks#1455]
Hello! Try to scan a broken git repo and got next error

```

└─$ gitleaks detect --source ./ -v              

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:19AM ERR [git] fatal: unable to read fa44a407bfe0f6172ff3fb7de7fb962484b1e606
10:19AM ERR  error="stderr is not empty"
10:19AM INF scan completed in 3.03ms
10:19AM INF no leaks found

```

Is it possible to continue work in this case? Try to find anything what possible. 
Thanks.

**Comment by rgmz** [comment]
What's the output if you do `git log -p -U0 --full-history --all`?

The repository may be broken and in need of repair (e.g., https://stackoverflow.com/a/1507935).

**Comment by hvprvtr** [comment]
Thanks!
