### ISSUE TITLE
square-access-token Rule matches for Docker Image Digest (False Positives)

### ISSUE THREAD

**Issue by very-doge-wow** [gitleaks/gitleaks#1468]
**Describe the bug**
We're using gitleaks 8.18.4 (the latest version) to scan our git repositories as well as some other artifacts for leaked secrets every night. Since today, we're seeing a lot of false positives, where gitleaks supposedly found a leak for the rule id "square-access-token".

As an example, this is the line of code where the leak is supposedly found:

```yaml
image: my-super.registry.docker/aws-cli@sha256:eaaa7b11777babe28e6133a8b19ff71cea687e0d7f05158dee95a71f76ce3d00
```

This is the exact finding:

```json
{
  "Description": "Detected a Square Access Token, risking unauthorized payment processing and financial transaction exposure.",
  "StartLine": 322,
   "EndLine": 323,
  "StartColumn": 79,
  "EndColumn": 1,
  "Match": "REDACTED",
  "Secret": "REDACTED",
  "File": "base-images-and-pinned-package-versions.yaml",
  "SymlinkFile": "",
  "Commit": "",
  "Entropy": 3.70544,
   "Author": "",
  "Email": "",
  "Date": "",
  "Message": "",
  "Tags": [],
   "RuleID": "square-access-token",
  "Fingerprint": "base-images-and-pinned-package-versions.yaml:square-access-token:322"
}
```

The start column matches exactly to the digest of the image (not in my given example as I have redacted the real registry host).

**To Reproduce**

1. Create a file with this content:

```yaml
aws-cli@sha256:eaaa7b11777babe28e6133a8b19ff71cea687e0d7f05158dee95a71f76ce3d00
```

2. Scan the directory using `gitleaks detect --no-git .`

3. Inspect the found leak.

**Expected behavior**
Digests of Docker images should not be treated as leaks.

**Screenshots**
![image](https://github.com/user-attachments/assets/0b6c3adb-f9e9-4438-86b7-7fca2f9a4142)

**Basic Info (please complete the following information):**
 - OS: MacOS, debian
 - Gitleaks Version: 8.18.4

**Additional info**
I suspect maybe the rule matches because the digest starts with `eaaa`.

cc @zricethezav

**Comment by rgmz** [comment]
Case-insensitivty may be the issue here. It _seems_ like the pattern should only match `EAAA` and not `eaaa`.

https://github.com/gitleaks/gitleaks/blob/c0fda4358e64742a8a7aac4fee4f3162d344a25c/cmd/generate/config/rules/square.go#L13-L14
