### ISSUE TITLE
gitleaks doesn't work anymore

### ISSUE THREAD

**Issue by lucacome** [gitleaks/gitleaks#1505]
**Describe the bug**
I'm usually using `gitleaks` through `pre-commit` and I noticed that it stopped working with the latest update, so I tried with docker and I see the same behavior

**To Reproduce**

```
❯ docker run -v $(pwd):/path zricethezav/gitleaks:latest git -v

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

2:05AM FTL flag accessed but not defined: source
```

**Expected behavior**
it works?

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: MacOS and Docker
 - Gitleaks Version: v8.19.0

**Additional context**
```
docker run -v $(pwd):/path zricethezav/gitleaks:latest --version
gitleaks version v8.19.0
```

cc @zricethezav

**Comment by rgmz** [comment]
I suspect this would be caused by #1504.

**Comment by jtmilanest** [comment]
It was released just an hour ago - an end-of-the-week nightmare! :melting_face:

**Comment by zricethezav** [comment]
Should be fixed now, sorry about that.
