### ISSUE TITLE
Running gitleaks detect with source returns no leaks

### ISSUE THREAD

**Issue by jbyardi** [gitleaks/gitleaks#1510]
**Describe the bug**
When running the following gitleaks detect --no-git and supplying a source directory the program does not detect any leaks. When I remove source and change the current working directory to what I want to scan, leaks are detected.

You can see in the screenshot the 0 leaks (--source) and 8 leaks found (no --source supplied).

To confirm, does the --source argument allow you to specify a directory or file to scan? Or does it do something else?

**To Reproduce**
Run: gitleaks detect --source C:\path\to\files --no-git

**Expected behavior**
When supplying source it should scan the specified files and detect leaks.

**Screenshots**
![image](https://github.com/user-attachments/assets/5c32d3c0-0fab-43f9-bfbf-f642c3abc8fd)

**Basic Info (please complete the following information):**
 - OS: Windows 11
 - Gitleaks Version: 8.19.2

**Comment by rgmz** [comment]
I'm not able to reproduce this (on Linux). Can you share the command output with `--log-level trace`? Also, does the path need to be redacted? It may be important to reproducing the issue.

```sh
$ ./gitleaks detect --source ~/dev/github.com/gitleaks/test-secrets --no-git

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:38AM INF scan completed in 8.23ms
10:38AM WRN leaks found: 6

$ cd ~/dev/github.com/gitleaks/test-secrets
$ /tmp/gitleaks/gitleaks detect --no-git

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:39AM INF scan completed in 2.64ms
10:39AM WRN leaks found: 6
```

**Comment by JoostVoskuil** [comment]
@jbyardi maybe something stupid, but can you reverse your slashes?
gitleaks detect --source C:/path/to/files --no-git

**Comment by jbyardi** [comment]
Okay this can be closed. Turns out the file path that I was hiding had the word "vendor" in it. Found out by copying the file elsewhere, renamed it and it was able to detect leaks.

The word vendor is in the global allow list by default in the config file. Looks like I'll need to supply a custom config file to remove that allow.

--log-level trace did not show any extra details. 

Thanks for entertaining my nonsense!

**Comment by rgmz** [comment]
> --log-level trace did not show any extra details.

Hmm, that may be useful for debugging.
