### ISSUE TITLE
gitleaks command dont have '--log-opts' argument in latest version

### ISSUE THREAD

**Issue by bpoorva** [gitleaks/gitleaks#1530]
**Describe the bug**
gitleaks command dont have '--log-opts' argument in latest version

**To Reproduce**
1.Download gitleaks version 8.19.2
2. Execute command - gitleaks.exe
3. Look for '--log-opts' argument in the output.

**Expected behavior**
gitleaks help output shoud show '--log-opts' argument

**Screenshots**
PFA
![gitleaks-8 18](https://github.com/user-attachments/assets/fc24a14c-69b9-442c-b644-e449a94ba66c)
![gitleaks-8 19](https://github.com/user-attachments/assets/3aba88d6-8ae4-4411-8302-bcb889a97745)

**Basic Info (please complete the following information):**
 - OS: Windows
 - Gitleaks Version: 8.18.4 & 8.19.2

cc @zricethezav

**Comment by rgmz** [comment]
@bpoorva It seems the help options were inadvertently changed by #1504.

The flag still exists if you do `gitleaks detect` or the new `gitleaks git`.

**Comment by zricethezav** [comment]
Whoops, you're both right. The default gitleaks behavior is to scan the CWD as a git repo. As such, `gitleaks` without a command should accept `log-opts` in order to maintain backwards compat from 8.19.0

**Comment by zricethezav** [comment]
whoops, you're totally right. Thanks for raising that issue.
