### ISSUE TITLE
Rate limit reached on app.keygen.sh

### ISSUE THREAD

**Issue by piotrekkr** [gitleaks/gitleaks#1561]
I think there is a problem with API limit on keygen.sh

```
Daily API request limit of 2,000 has been reached for your account. Please add a payment method at https://app.keygen.sh/billing to continue.
```

![image](https://github.com/user-attachments/assets/3a298b0c-69fb-4b11-9996-3cf4099a9ed7)

**Comment by xSAVIKx** [comment]
We've experiencing the same issue

**Comment by enric0r-s** [comment]
@zricethezav Did something change on keygen.sh side?

**Comment by ehdieunguyen** [comment]
We've experiencing the same issue!

**Comment by bheemuni-raju** [comment]
same here as well

**Comment by kgapos** [comment]
Same issue here

**Comment by AlanSower** [comment]
Same for us here.

**Comment by zricethezav** [comment]
Update the version. Keygen is declining my card so I just ripped out the check. Also this is a Gitleaks-action issue, not a Gitleaks issue. Closing

**Comment by zricethezav** [comment]
Or pin to v2

**Comment by zricethezav** [comment]
I’ll be trying to get a working payment method tomorrow. I’m away from my computer today so I won’t get to it today. But yea in the meantime just pin to v2 or update to v2.3.7

**Comment by zricethezav** [comment]
Whoops, I’ll update the release notes. I released them kind of frantically yesterday. Sorry for the inconvenience of updating versions :/
