### ISSUE TITLE
8.21.0, Custom gitleaks.toml Introducing False Positives

### ISSUE THREAD

**Issue by createchange** [gitleaks/gitleaks#1571]
**Describe the bug**

I have been using the Gitlab secrets detection analyzer, via Compliance Pipelines, for quite a while now. There is little support offered for extending the ruleset, so I have created the following, which:

- [defines file used by gitlab to state a custom ruleset is going to be used](https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#create-a-ruleset-configuration-file) - this is pulled from an internal repo
- Retrieves the `gitleaks.toml` config file from the master branch of the Gitleaks repo
- Merges the two files, as to append our custom rules to the rules provided by Gitleaks

```
include:  
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml

secret_detection:
    stage: compliance-scanning
    before_script:
            - echo "Adding custom Secret Detection ruleset files"
            - mkdir -p .gitlab
            - echo "Retrieving Gitleaks default config..."
            - 'wget --header "PRIVATE-TOKEN: ${SECURITY_POLICIES_READ_REPO_TOKEN}" "${CI_API_V4_URL}/projects/<my-group>%2Fgitlab-security-policies%2Fpolicies/repository/files/.gitlab%2Fsecrets-detection%2Fsecret-detection-ruleset.toml/raw" -O .gitlab/secret-detection-ruleset.toml'
            - 'wget https://raw.githubusercontent.com/gitleaks/gitleaks/9988e5224c05eac1cce8501c8951e67566bbf0a8/config/gitleaks.toml -O .gitlab/gitleaks.toml'
            - echo "Synthesizing default config with Strive-specific rules"
            - |
                cat <<EOT >> .gitlab/gitleaks.toml
                [[rules]]
                description = "Check for rule-1"
                id = "rule-1"
                regex = '''custom_regex_1'''

                [[rules]]
                description = "Check for rule-2"
                id = "rule-2"
                regex ='''custom_regex_2'''
                EOT
```

I have found that after the 8.21.0 updates, we are experiencing false positives. We are also experiencing true positives - both custom rules and default gitleaks rules are triggering as expected.

Here are a couple example lines that are being detected as `generic-api-keys`:

- `actv_chargedetail.licensekey = diag_row_11.licensekey`
- `and patient_list.client_id = acp_rolling12.client_id`

**To Reproduce**

See above, can provide more information privately if helpful.

**Expected behavior**
False positives refrain from occurring. 

**Screenshots**
N/A

**Basic Info (please complete the following information):**
 - OS: Gitlab Secrets Detection Runner
 - Gitleaks Version: 

cc @zricethezav

**Comment by rgmz** [comment]
> I have found that after the 8.21.0 updates, we are experiencing false positives. We are also experiencing true positives - both custom rules and default gitleaks rules are triggering as expected.
> 
> Here are a couple example lines that are being detected as `generic-api-keys`:
> 
>     * `actv_chargedetail.licensekey = diag_row_11.licensekey`
> 
>     * `and patient_list.client_id = acp_rolling12.client_id`
>

Are these known false positives tracked in the `.gitleaksignore` file? If so, the issue may be https://github.com/gitleaks/gitleaks/issues/1570#issuecomment-2413947146.

**Comment by createchange** [comment]
Hi @rgmz , thanks for the quick response and suggestion. We are not manually track false positives via `.gitleaksignore`. Rather, we are using the built-in Gitlab security vulnerability to classify findings. Additionally, I cross-referenced historical findings to see if they were possible marked as false positives in the past, but this is the first instance of these findings occurring.

**Comment by zricethezav** [comment]
@createchange another thing that would be useful is letting us know the command you were using. `git` vs `dir` (detect --no-git).

**Comment by createchange** [comment]
> Hmm, none of [the changes in v8.21.0](https://github.com/gitleaks/gitleaks/releases/tag/v8.21.0) jump out as an obvious cause to seeing additional false positives.
> 
> > I have found that after the 8.21.0 updates,
> 
> To confirm, this doesn't happen with the version prior (v8.20.1)?

It does not. I made a minor error in my initial post. When I experience the false positives, I am merging my own definitions with:

https://raw.githubusercontent.com/zricethezav/gitleaks/master/config/gitleaks.toml
 
However, when I merge with the file before the most recent commit:
 
https://raw.githubusercontent.com/gitleaks/gitleaks/9988e5224c05eac1cce8501c8951e67566bbf0a8/config/gitleaks.toml

I experience no such false positives.

**Comment by createchange** [comment]
> @createchange another thing that would be useful is letting us know the command you were using. `git` vs `dir` (detect --no-git).

Thanks for offering up your contact info - I'll be reaching out. 

Judging from this file, it looks like the Gitlab team is using `git` in their analyzer: https://gitlab.com/gitlab-org/security-products/analyzers/secrets/-/blob/master/analyze.go?ref_type=heads

**Comment by zricethezav** [comment]
@createchange 
Ahh! I think I know what's goofed here. GitLab is using  < `v8.21.0` which does not support `[[rules.allowlists]]` syntax. The `master` branch uses `[[rules.allowlists]]` in the default config. So effectively the config that gitleaks `< v8.21.0` ends up using does not have any valid allowlists since master uses the new syntax. Hopefully that makes sense. This could be considered a breaking change so we will update the default config to use the old syntax which will give teams time to upgrade their gitleaks version (give it about a month of two).
