### ISSUE TITLE
Improving rule 'generic-api-key' to avoid false positives on e.g. "public_key=", "monkey=", ...

### ISSUE THREAD

**Issue by Ben-grmbl** [gitleaks/gitleaks#1578]
**Is your feature request related to a problem? Please describe.**

I am getting a lot of false positives with the rule 'generic-api-key'.
Currently, the rule searches for `key|api|token|secret|client|passwd|password|auth|access` in close vicinity to a random-looking string

This will currently match e.g. the following false positives:
```
public_key = "Gc3Q0RXJM2CUNbgKpUMnkPtOfOzeFzsW"     (this is intended to be public)
MantleAPI_version=9a038989604e8da62ecddbe2094b16ce1b778be1     (this is a git commit hash, used for versioning)
LLM_SECRET_NAME = "NEXUS-GPT4-API-KEY"         (entropy 3.7, this is merely the name of the environment variable)
keyword	= "Befaehigung_P2"     (entropy 3.5)
<Object mapKey="R648-MF-DEPARTURE" ... >  (entropy 3.5)

// from https://github.com/microsoft/vcpkg/blob/master/scripts/ci.baseline.txt
minisat-master-keying:x64-uwp=fail
monkeys-audio:mx64-uwp=fail
rapidstring:marm64-uwp=fail
```

**Describe the solution you'd like**

I would like to exclude certain keywords from the match:
- `public_key, public_token`, because clearly they are meant to be public
- `keyword, monkey, donkey, keyboard, rapid, capital, ...`, because they merely contain the string api/key
- `secret_name, client_name, ...`, because the name of a secret is not a secret
- `api_version, client_version`, the version of an api should not be secret.
- `fake_secret, dummy_password`, ...
- ...

I think a manageable list of ~20 such keywords would cover >90% of false positives of this specific type

In order to do this, I suggest adding some regexes to the current AllowList, e.g.:
```golang
+ MatchCondition: config.AllowlistMatchOr,
+ Regexes: []*regexp.Regexp{
+ 	regexp.MustCompile(`(?i)` +
+ 		`(public.?key|public.?token` + // public key -> not a secret
+		`|api.?version|client.?version` + // version info -> not a secret
+		`|map.?key|key.?word|monkey|donkey|keyboard|keying|keystone` + // common words containing "key"
+		`|rapid|capital` + // common words containing "api"
+		`|secret.?name|client.?name|key.?name` + // name of secret, not the secret itself
+		`|fake|dummy)`),  // 
+ },
+ RegexTarget: "match",
  StopWords:   DefaultStopWords,
```

in order to make RegexTarget: "match" work for the allowList regex, the secret matching regex would have to be slightly modified:
```
Regex: utils.GenerateSemiGenericRegex([]string{
!	`\w{0,10}key`,      // <- to include e.g. "public_key", "rapid" in the capture
!	`\w{0,10}api`,
!	`\w{0,10}token`,
!	"\w{0,10}secret",  // <- to include e.g. "fake_secret, "dummy_secret" in the capture
	"client",
	"passwd",
	"password",
	"auth",
	"access",
}, `[0-9a-z\-_.=]{10,150}`, true),
```
With that, RegexTarget: "match" can be used. RegexTarget: "line" is suboptimal, because a single line could contain e.g. a public_key **and** a secret key.

**Describe alternatives you've considered**

- With negative look-behind / look-ahead groups this could be accomplished with only the secret matching Regex, without having an allowList regex. I believe those are not supported by the current regex implementation.

- Tinkering with the minimum entropy might also help reduce some of the false positives? The current value of 3.5 seems very low, based on the examples above.

**Additional context**

I'd be happy to create a pull request for this.

If there is anything I missed, or if there is a problem with this approach, please let me know.
I would also be interested in alternative approaches.

cc @zricethezav

**Comment by rgmz** [comment]
> I would like to exclude certain keywords from the match:
> 
>     * `public_key, public_token`, because clearly they are meant to be public
> 
>     * `keyword, monkey, donkey, keyboard, rapid, capital, ...`, because they merely contain the string api/key
> 
>     * `secret_name, client_name, ...`, because the name of a secret is not a secret
> 
>     * `api_version, client_version`, the version of an api should not be secret.
> 
>     * `fake_secret, dummy_password`, ...

Partually related to #1492, as I don't think anything left of the identifier is currently captured in the match.

**Comment by rgmz** [comment]
Two other `key` related matches that could probably be excluded: 'primary key' and 'natural key'. I have yet to encounter a true positive with them.

```regex
\b(natural|primary)[_.-]?key\b
```

**Comment by Ben-grmbl** [comment]
I added most of the *key*related exceptions to my pull request.

> `key="..." value="..."` and `key="..."\nvalue="..."` (the latter should be handled by another rule... not sure how we'd exclude it with just the match or line)

Would that not work with something like this (unoptimized):
```golang
Regex: regexp.MustCompile(utils.GenerateSemiGenericRegex(...)).String() + `(?:[^\n\w]{0,10}\n?[^\n\w]{0,10}[\w.-]{0,20}[^\n\w]{0,5})`)
```
that would put `key="..."\nvalue=` into the `match` context, so it could be caught by an allowList regex?
