### ISSUE TITLE
False positives for curl-auth rule if variables are quoted

### ISSUE THREAD

**Issue by very-doge-wow** [gitleaks/gitleaks#1589]
**Describe the bug**
The new rule `curl-auth-user` is supposed to find leaks of basic auth credentials used with curl by determining if the curl command was called with the `-u` or `--user` flag, where the value contains a leaked secret (i.e. the credentials of an account).

However, the rule also matches if the flag is used in a script with variables. This is not a leak, as the environment variables are retrieved through other means and never committed to source code or any artifacts.

**To Reproduce**

Create a file `test.sh` (example AQL call to Artifactory):

```sh
curl -sSf -u ${USER}:${PASSWORD} \
    -H "content-type: text/plain" \
    -X POST 'https://xxx.com/artifactory/api/search/aql' \
    -d @query.aql \
    > output.json
```

Run gitleaks and inspect the finding.

> ...
Finding:     curl -sSf -u REDACTED \
Secret:      REDACTED
RuleID:      curl-auth-user
Entropy:     4.169890
...

If the quotes around the value passed using `-u` are removed, the false positive disappears. This means the rule must be fixed to not simply match if quotes are given.

**Expected behavior**
Variables do not match the rule, even if they are quoted, as they are a valid way to pass the credentials without leaks.
One wants to quote variables to prevent word-splitting and globbing.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS: MacOs
 - Gitleaks Version: v8.21.1

**Additional context**
You can also verify the behavior with regex101:
https://regex101.com/r/LcccLw/1

cc @zricethezav

**Comment by rgmz** [comment]
Thanks for the detailed report, @very-doge-wow. This seems to be an issue with one of the allowlist patterns, causing it to not match `${...}`.

https://github.com/gitleaks/gitleaks/blob/d03d6c401b51633afc8e9d2b37cf3700927de595/config/gitleaks.toml#L286

[This change in #1586](https://github.com/gitleaks/gitleaks/pull/1586/files#diff-70ab8aa79cde1f4ef1eb6e1020fa304816ef7cf2e2974ae560b1a9349172061bR27) should fix that, once merged.
