### ISSUE TITLE
Support for Continuing on Permissions Error

### ISSUE THREAD

**Issue by joshfinley** [gitleaks/gitleaks#1617]
**Is your feature request related to a problem? Please describe.**
There does not appear to be a way to continue scanning if a permissions error is encountered. 

**Describe the solution you'd like**
A flag that allows GitLeaks to continue despite permissions errors. One permission denied error should not make the tool useless.

**Describe alternatives you've considered**
Adding un-allowed folders to `gitleaksignore`. This is a very messy solution because you cannot always predict permissions errors.

cc @zricethezav

**Comment by zricethezav** [comment]
@joshfinley could you provide some more context like the error message or log trace?

**Comment by rgmz** [comment]
I'm assuming that returning any error from fs.Walk (when using dir) causes it to abort.

**Comment by joshfinley** [comment]
> I'm assuming that returning any error from fs.Walk (when using dir) causes it to abort.

Correct. I now see the pending PR you referenced that might solve this.
