### ISSUE TITLE
Regex works doesn't correct

### ISSUE THREAD

**Issue by almaz045** [gitleaks/gitleaks#1631]
**Describe the bug**
Gitleaks does not find all the secrets, although the regex is correct and everything is ok here + field "Secret" is not filled: 
https://regex101.com/r/zAaY2U/1
https://regex101.com/r/oSNiUu/1

**To Reproduce**
1. Add my private-rule like in url above: 
(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY[a-z ]{0,6}-----[\s\S-]{20,}?KEY[a-z ]{0,6}-----
2. Generate private keys or download my file
3. Run gitleaks latest on this file with my rule:
gitleaks detect -c current.toml -s keys.txt --no-git -v
**Expected behavior**
all 10 secrets are found + field "Secret" is filled

**Screenshots**
<img width="533" alt="изображение" src="https://github.com/user-attachments/assets/4dde1cea-1474-4a78-b47f-7c019e58df0c">
![изображение](https://github.com/user-attachments/assets/3778a7b3-70b2-439c-aa5f-4b538b5acc5a)

[keys.txt](https://github.com/user-attachments/files/17699029/keys.txt)

**Basic Info (please complete the following information):**
 - OS: MacOS, Linux
 - Gitleaks Version:
 8.21.0

**Additional context**
I noticed that problem started since 8.18.1 
cc @zricethezav

**Comment by almaz045** [comment]
> @almaz045 This is a small bug with how we determine what the "secret" is.
> 
> You can easily fix it on yourself by only using capture groups if the encompass the whole secret. Anything else should be a non-capturing group:
> 
> ```diff
> -( BLOCK)?
> +(?: BLOCK)?
> ```

Thanks for the answer. The second problem is that out of 60 keys that are in regex101, gitleaks detects 50. Although the regex is the same: https://regex101.com/r/PmAzy3/1

docker run -v /yourpath:/path/ zricethezav/gitleaks:latest detect -c /path/original.toml -s/path/keys.txt --no-git -v -l trace

![изображение](https://github.com/user-attachments/assets/c11b1ade-82eb-449c-9c65-fbafd8499f22)

**Comment by rgmz** [comment]
> Thanks for the answer. The second problem is that out of 60 keys that are in regex101, gitleaks detects 50. Although the regex is the same: https://regex101.com/r/PmAzy3/1

This looks like an issue with chunking. If I manually increase the chunk size, the number of secrets detected changes. FYI @zricethezav 

https://github.com/gitleaks/gitleaks/blob/7f77987d91c590e021d9fa2b3c0e57c4a4376147/detect/detect.go#L25

```sh
# 20kb
8:37AM INF scan completed in 80.9ms
8:37AM WRN leaks found: 55

# 50kb
8:38AM INF scan completed in 82.4ms
8:38AM WRN leaks found: 58

# 100kb
8:38AM INF scan completed in 80.7ms
8:38AM WRN leaks found: 59
```

**Comment by rgmz** [comment]
> Thanks for the answer. The second problem is that out of 60 keys that are in regex101, gitleaks detects 50. Although the regex is the same: https://regex101.com/r/PmAzy3/1

@almaz045 Do you mind closing this issue since your original problem was solved? 

I've created #1651 to track this new issue you've highlighted.
