### ISSUE TITLE
Error downloading go toolchain with >=8.21.3

### ISSUE THREAD

**Issue by dpinol** [gitleaks/gitleaks#1681]
**Describe the bug**
Error downloading go toolchain with >=8.21.3. Works fine with 8.21.2

**To Reproduce**
```
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.0
    hooks:
      - id: gitleaks
```
`pre-commit run --all gitleaks
`

**Screenshots**
```
[INFO] Installing environment for https://github.com/gitleaks/gitleaks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/local/go/bin/go', 'install', './...')
return code: 1
stdout: (none)
stderr:
    go: downloading go1.23 (linux/amd64)
    go: download go1.23 for linux/amd64: toolchain not available
Check the log at /home/dani/.cache/pre-commit/pre-commit.log
```

**Basic Info (please complete the following information):**
 - OS: ubuntu 24.10
 - Gitleaks Version: 8.21.3, 8.21.4 & 8.22.0

**Additional context**
This solves the problem
```
diff --git a/go.mod b/go.mod
index e6c1657..6fca2ff 100644
--- a/go.mod
+++ b/go.mod
@@ -2,6 +2,8 @@ module github.com/zricethezav/gitleaks/v8
 
 go 1.23
 
+toolchain go1.23.4
+
```

cc @zricethezav

**Comment by rgmz** [comment]
What version of Go are you using?

These types of errors seem to be a growing pain with Go's toolchain feature: https://github.com/golang/go/issues/62278, https://github.com/golang/go/issues/65568. Incompatibility between versions has come up before, such as #1544.

**Comment by dpinol** [comment]
I use 1.21.1.
After upgrading my system Go to 1.23.4, everything worked fine.
However, what's wrong about keeping `toolchain go1.23.4` in your code as you had for 1.22 in the past?

**Comment by rgmz** [comment]
I believe the `toolchain` directive is automatically managed by Go. v8.21.3 contained an update to Go 1.23.

https://github.com/gitleaks/gitleaks/releases/tag/v8.21.3
