### ISSUE TITLE
Junit-Support

### ISSUE THREAD

**Issue by strowi** [gitleaks/gitleaks#404]
**Is your feature request related to a problem? Please describe.**
It's always hard to filter and/or read results on a ci/cd system from json. 
Also visually in a browser.

**Describe the solution you'd like**
JUnit is a widely used format, that can be parsed by a wide range of ci/cd systems including Gitlab + Jenkins. This would help failing builds on results and make them more readable.

**Describe alternatives you've considered**
Parsing Json, converting to tables.

**Additional context**
https://docs.gitlab.com/ee/ci/junit_test_reports.html

cc @zricethezav

regards,
strowi

**Comment by zricethezav** [comment]
I will happily accept a PR for this idea
