### ISSUE TITLE
Backward-compatible --version command line option?

### ISSUE THREAD

**Issue by joealba** [gitleaks/gitleaks#773]
**Is your feature request related to a problem? Please describe.**

Thanks for creating gitleaks!  It's a handy tool, for sure.  The recent command line changes do simplify the options and code quite a bit, but I'd like to propose a backward-compatible consistent way to retrieve the version number so any tooling like pre-commit hooks can be built to be version-aware in a straightforward way for projects with multiple devs.

**Describe the solution you'd like**

Support a `--version` command line option in version 8 and going forward

**Describe alternatives you've considered**

Something like `gitleaks --help | grep -q "\-\-version" && gitleaks --version || gitleaks version` works fine too, but the `--version` and/or `-v` idioms are quite common across *nix command line tools.

Thanks for your consideration and your efforts in maintaining a helpful tool!  I'll work on a PR too, but I wanted to submit the feature request to get the thoughts of the maintainers here as well.

cc @zricethezav

**Comment by zricethezav** [comment]
@joealba here ya go! https://github.com/gitleaks/gitleaks/commit/26f34692fac6e9daec13c770421b4ed990d1c321

better late than never ;)
