### ISSUE TITLE
Enhance CONTRIBUTING documentation

### ISSUE THREAD

**Issue by weineran** [gitleaks/gitleaks#921]
https://github.com/zricethezav/gitleaks/blob/0d471653b5389029ab9126c35ea960b480114135/CONTRIBUTING.md?plain=1#L41
* There is not actually a section called "regex". It probably refers to the paragraph that begins with `generateSemiGenericRegex`. It would probably be more clear to have a section header.

https://github.com/zricethezav/gitleaks/blob/0d471653b5389029ab9126c35ea960b480114135/CONTRIBUTING.md?plain=1#L71-L75
* Assuming "should" uses roughly the [RFC definition](https://datatracker.ietf.org/doc/html/rfc2119#section-3), it would be good to know in what cases one might choose to use different keywords vs identifiers.
* Generally, it would be good to know what is the difference between keywords vs identifiers

https://github.com/zricethezav/gitleaks/blob/0d471653b5389029ab9126c35ea960b480114135/config/gitleaks.toml#L162-L169
* Although perhaps it's obvious, it might good to discuss how each item in the {provider}.go file maps to each item in the generated rule above.

**Comment by zricethezav** [comment]
contributing docs rock dude what are you talking about ;P

gonna close this though for now though. happy to accept PRs making improvements to the docs
